language: java
jdk: openjdk11
env:
  global:
  - secure: e/KLtCw9h5Px08s8M33rOtm9e/pCgBDM8v6po7bML6DmYViNf8Zzy9ZtpqGbZxja+PhnmOigYc2lMv5TQjemIHyUBebCWeDRBaOZjaP/LrmRdmSJqnyUcgGuq6HfaDzPoNEO/b707T5hUipruP2JD0wXYrOSN6vl5eU5sC1QkeNBkwu8T+IsNEwQSwNqjfjiqMVyVLOh4iioPfnXElyTbIZuQ2QtjPrPd2c0oQFRqXJz54acygVUJrljvxRBEHPFxmSGfaEPywph5AqFv7Us+yYS06qwh3gV1MRBgoQXUM4i1cR/i2G9jWmpS6lVqO9g7uDK/0OHgtHVCgSN9152njtTDfYvQdrKM+qfs5GErifueUYL4RuRH+8bNs6eH5sjPlW2HSqdjokXNZi4kgWnpP90/tM50xAE+oDZ9QQMRF4mETqDCCu8Jue/RzfuT+9wIjrn3j6npkJ5PKpxJgXv+AUeoHpsmepGJR5CpMqzZapSgaIf5kBcbIVVwv6McyRg4xbTuyve++9txYvHBJrkrDDroTzvpI1c9Gr3uJzFA6dtdq6X5fOq+u8Dml6o+4HYRvlGGhqWhU2+mfVA1XnVe5CAkwwMJTvzid+4KRwTa2VRCBF+7ORWWoL2abjh5iqLG6cqoip4vlM62b/kwPGO6OHgqk/1aWm9kr92PM7j1Jk=
  - secure: XmZVcoOtlqv0MGj3dW1rY8Q24sKPDU51baUen9WWaQ5X4OVb+V8ytwmJQovEG/8tsHJaxcqrKbbhRq4fYH3YohKAG0bn78F0AOCqkvlST3HplUrPn9/gi0jxPYpbRA7jfj3bRETBUDLAe1O7pbRv2fj1Z9dHhrVYLCcWsJj2jzZSGFWLfGSK6Id8mnBWglfCBohqo3laWKkdVdeu9VjsrxbzT91J8l2i+Xsa+M/vunTrpvZzWuUFYqqapl/Fvh6b2B8tlt81GFGm+U1H1nSgBysQ0PLz/PSgUzuyZ/mKNxiUJ3ot8Ka0RrEgpgc9kzC7cg4tZVnHqgAl7EREbrna84ZgsQDd6FJs5yfcOrzVOHV7N/14Kw3FTDw52VAD1yWRiWdMkqu8V1N5zP78VnIIB/1UEew6Tmp6n0gEFIC4U2GQzWeNwob6dQIfybCLXkAyQzkmS0I9VoiztC6SxLSWiD3lRu8jX7uX7njWW9oCFZ+b2QC5QjJTKnIn3cIKD856sLFj0ZurBZi2hB8bgo4FLVeFdYBW5X13r4oPXqUupB1QnCFFMgNw4JShsnw+JEIekCihdQXU8zjEDb2BkMml01TKPuWPi9qkWyysVhITqROgB6UDS2LS48chgmUUAVVLXsmBCJd93D1r7joEL7/a73C1CEyjajmT6vgTuqkyHvU=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
